cursor #c6c7d0
cursor_text_color #9ca0af

foreground            #c6c7d0
background            #11131a
selection_foreground  #00163a
selection_background  #243962
url_color             #6c9fff

color0   #11131a
color1   #ff5d8a
color2   #6cff81
color3   #fff75d
color4   #4a84f2
color5   #002876
color6   #6c9fff
color7   #edf3ff
color8   #979ca5
color9   #ff90af
color10  #98ffa7
color11  #fffa98
color12  #82adff
color13  #98bbff
color14  #bcd3ff
color15  #f7faff
