-- Auto-generated by DMS Matugen hook — do not edit manually.
-- Remove require("dms.colors") from hyprland.lua to override.

hl.config({
	general = {
		col = {
			active_border = "rgb(6c9fff)",
			inactive_border = "rgb(7b7f8e)",
		},
	},
	group = {
		col = {
			border_active = "rgb(6c9fff)",
			border_inactive = "rgb(7b7f8e)",
			border_locked_active = "rgb(ff7669)",
			border_locked_inactive = "rgb(7b7f8e)",
		},
		groupbar = {
			col = {
				active = "rgb(6c9fff)",
				inactive = "rgb(7b7f8e)",
				locked_active = "rgb(ff7669)",
				locked_inactive = "rgb(7b7f8e)",
			},
		},
	},
})
