source /home/$USER/.cache/wal/colors-hyprland

general {
    lock_cmd = pidof hyprlock || hyprlock
    ignore_dbus_inhibit = /opt/spotify/spotify
}

listener {
    timeout = 100
    on-timeout = hyprdvd -s
}
listener {
    timeout = 800
    on-timeout = source /home/$USER/.cache/wal/colors.sh && notify-send "System" "You are about to be locked out!" -i $wallpaper
}
listener {
    timeout = 1000
    on-timeout = loginctl lock-session
    on-resume = sleep 2 && source /home/$USER/.cache/wal/colors.sh && notify-send "System" "Unlocked! Hey $USER" -i $wallpaper
}

listener {
    timeout = 2400
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}
